matrix.o: matrix.c matrix.h
mmu_manager.o: mmu_manager.c hardware.h hw_config.h swap.h
oracle.o: oracle.c hw_config.h matrix.h
swap.o: swap.c swap.h hardware.h hw_config.h
user_process.o: user_process.c hw_config.h matrix.h
